userName: YOUR_NAME
authToken: YOUR_TOKEN
notebook: YOUR_NOTEBOOK_OF_EVERNOTE

openLinkApp:
  defaultNativeName: YOUR_MAC_NAME
  clouds:
    - name: iCloud
      natives:
        - name: YOUR_MAC_NAME
          prefix: file://
          path: /YOUR_HOME/AutoEvernote/test_data/iCloud
        - name: YOUR_PC_NAME
          path: C:\YOUR_HOME\AutoEvernote\test_data\iCloud
    - name: Dropbox
      natives:
        - name: YOUR_MAC_NAME
          prefix: file://
          path: /YOUR_HOME/AutoEvernote/test_data/Dropbox
        - name: YOUR_PC_NAME
          path: C:\YOUR_HOME\test_data\Dropbox
    - name: GoogleDrive
      natives:
        - name: YOUR_MAC_NAME
          prefix: file://
          path: /YOUR_HOME/AutoEvernote/test_data/GoogleDrive
        - name: YOUR_PC_NAME
          path: C:\YOUR_HOME\test_data\GoogleDrive